### ISSUE TITLE
[Feature] Build M1 Mac ARM64 Images

### ISSUE THREAD

**Issue by spuder** [deezer/spleeter#717]
Docker images are currently built for intel/amd only. 

It would be nice to have M1 mac Arm builds

## How to do this

1. Use buildx with docker. It nativly supports multi platform builds
2. Add the platform to the github action

Here is [an example](https://github.com/spuder/stl2origin/blob/master/.github/workflows/dockerhub.yaml#L33)

```
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: spuder/stl2origin:latest
          ```
